global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['3.10.175.149:9090'] #hosts of your prometheus
  - job_name: 'blackbox'
    static_configs:
      - targets: ['3.10.175.149:9115'] #hosts of your expoeter